Feature/task 3/implementation
leramovie/Netology_Industry_HW3 pull request #1
Opened 2021-01-14 13:08 UTC by leramovie

Первая часть 3-ей домашней работы выполнена.

2021-01-18 08:02 UTC, TrueMax requested changes

2021-01-18 08:02 UTC, TrueMax commented on NewVersionLera/Navigation/Screens/Login/Controller/LoginViewController.swift
> +class LoginViewController: UIViewController, LoginViewDelegate {
В задаче 2 предполагался как раз коллбэк у `LoginView`, но вы сделали через паттерн делегат. Ошибки тут нет, но в следующий раз постарайтесь переделать на коллбэк. Сейчас получилось некоторое нагромождение делегатов.

2021-01-18 08:02 UTC, TrueMax commented on NewVersionLera/Navigation/Screens/Login/Manager/AuthManager.swift
> +        return completion(Checker.shared.isLoginCorrect(login))
слово `return` тут лишнее: метод ничего не возвращает, мы просто передаем результат проверки в `completion`

2021-01-18 08:02 UTC, TrueMax commented on NewVersionLera/Navigation/Screens/Login/Manager/AuthManager.swift
> +        return completion(Checker.shared.isPasswordCorrect(password))
`return` лишнее

2021-01-18 08:02 UTC, TrueMax commented on NewVersionLera/Navigation/Screens/Login/Singletone/Checker.swift
> +    static var shared: Checker = {
почему `var`? 
https://www.hackingwithswift.com/example-code/language/what-is-a-singleton

2021-01-18 08:02 UTC, TrueMax commented on NewVersionLera/Navigation/Screens/Login/View/LoginView.swift
> +    weak var authDelegate: LoginViewControllerDelegate?
Почему в `LoginView` вдруг переменная типа, относящаяся к контроллеру? View еще не знает, какой контроллер его инициализирует. Лишнее.

2021-01-21 11:08 UTC, leramovie commented on NewVersionLera/Navigation/Screens/Login/Controller/LoginViewController.swift
> +class LoginViewController: UIViewController, LoginViewDelegate {
Остввила делегат для LoginView (Мне показалось интересным оставить такую связку, чтобы в дальнейшем посмотреть) 
Но сделала для FeedView и FeedViewController уже использование callback

2021-01-21 11:12 UTC, leramovie commented
Запушила новые изменения.
Сделала коллбэк для FeedView + FeedViewController и вторую часть 3-ей задачи.

2021-01-21 14:14 UTC, TrueMax requested changes
По второй задаче нужна доработка, если есть дополнительные вопросы, задавайте

2021-01-21 14:14 UTC, TrueMax commented on NewVersionLera/Navigation/AppDelegate.swift
> +        let storyboard = UIStoryboard(name: "Main", bundle: nil)
если мы используем SceneDelegate, в AppDelegate не надо ничего делать, получается задвоение определения `window`

2021-01-21 14:14 UTC, TrueMax commented on NewVersionLera/Navigation/Screens/Feed/FeedViewController.swift
> +    var output: FeedViewOutput?
для начала мы договорились эту зависимость в инициализаторе внядрять для большего контроля

2021-01-21 14:14 UTC, TrueMax commented on NewVersionLera/Navigation/Screens/Feed/FeedViewController.swift
> +              self?.output?.showPost()
в текущей конфигурации не нахожу инициализацию `PostPresenter`, который должен отвечать за пуш `PostViewController`, вместо этого в трех местах создается и пушится `postViewController`, чего быть не должно, инициализация должна быть изолирована от презентации, в `lazy var` свойство можно поместить контроллер, и когда нужно, он будет запушен в стек

2021-01-30 17:05 UTC, TrueMax approved these changes

2021-01-30 17:05 UTC, TrueMax commented on NewVersionLera/Navigation/SceneDelegate.swift
> +        //MARK: To MAKSIM ABAKUMOV Вот здесь у меня непонятки
формулируйте непонятки, будем разбирать

2021-01-31 11:16 UTC, leramovie commented
Добавила в appdelegate, после консультации Максима, т.к. были проблемы со сторибордом (при нажатии на кнопки в FeedViewController -ничего не происходило). Сейчас работает!

 func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
          
        guard let windowScene = (scene as? UIWindowScene) else { return }
        window?.windowScene = windowScene
        
        if let rootVC = window?.rootViewController as? UITabBarController,
           let feedNC = rootVC.viewControllers?[0] as? UINavigationController,
           let feedVC = feedNC.viewControllers[0] as? FeedViewController {
            let presenter = PostPresenter()
            feedVC.output = presenter
        }
    }

2021-01-31 11:17 UTC, merged